"""empty message

Revision ID: 77659f64e8b5
Revises: 8ecda8edde40
Create Date: 2020-11-10 21:12:37.142730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77659f64e8b5'
down_revision = '8ecda8edde40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###
