"""empty message

Revision ID: 8556fc9717f0
Revises: e62ec26f22fe
Create Date: 2020-11-04 19:48:34.327332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8556fc9717f0'
down_revision = 'e62ec26f22fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
