"""empty message

Revision ID: 8ecda8edde40
Revises: 5e97c3b17590
Create Date: 2020-11-10 21:08:02.592405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecda8edde40'
down_revision = '5e97c3b17590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'area_id')
    op.drop_table('areas')
    # ### end Alembic commands ###
